name: stevestomp
favicon: null
layout_spectrum: 0.85435
typography_spectrum: 0.4880117040593177
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c6e9f3'
    - '#ede115'
    - '#000000'
    - '#808080'
    - '#555555'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
